name: CI/CD con Docker y GitHub Actions - Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Loguearse en DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Construir y subir imagen del frontend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/front-docker-test -f Dockerfile .
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/front-docker-test ${{ secrets.DOCKERHUB_USERNAME }}/front-docker-test:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/front-docker-test:latest